/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class EvilMethodClass */

#ifndef _Included_EvilMethodClass
#define _Included_EvilMethodClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     EvilMethodClass
 * Method:    evilMethod
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_EvilMethodClass_evilMethod
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
